apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    some-label: pod
spec:
  containers:
  - name: maven-jdk-node
    image: maven:3.8.4-openjdk-8-slim
    command:
    - cat
    tty: true
  - name: docker
    image: docker:latest 
    volumeMounts:
    - name: dockersock
      mountPath: "/var/run/docker.sock"
    command:
    - cat
    tty: true
  # - name: kubectl 
  #   image: lachlanevenson/k8s-kubectl:latest
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  - name: hosts
    hostPath:
      path: /etc/hosts